name: tembeakenya
description: "Tembea Kenya is a hiking application to enhance hiking experience
  and community."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  app_settings: ^5.1.1
  connectivity: ^3.0.6
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.1.1
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  go_router: ^14.1.4
  http: ^1.2.1
  internet_connection_checker_plus: ^2.3.0
  json_annotation: ^4.9.0
  json_extractor: ^1.1.2
  mockito: ^5.4.4
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  shared_prefs_cookie_store: ^0.0.2
  image_picker: ^1.1.2
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  flutter_dotenv: ^5.1.0
  # mapbox_maps_flutter: ^2.0.0

dev_dependencies:
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

dependency_overrides: 
  mapbox_gl: ^0.15.0
  flutter_native_splash: ^2.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib\assets\fonts\Montserrat-Bold.ttf
        - asset: lib\assets\fonts\Montserrat-BoldItalic.ttf
          style: italic
        - asset: lib\assets\fonts\Montserrat-Light.ttf
          weight: 300
        - asset: lib\assets\fonts\Montserrat-LightItalic.ttf
          weight: 300
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  android: true
  ios: true
  web: false
  # color: "#161a0f"
  image: "lib/assets/images/logo.png"
  background_image: "lib/assets/images/mountbg.png"
  branding: "lib/assets/images/brand.jpg"