// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATnWvdBuRx3-m0wT4-ytBsnmDUq8ujMOg',
    appId: '1:903105583227:web:64c3df5066bcc26312aade',
    messagingSenderId: '903105583227',
    projectId: 'project-tembea',
    authDomain: 'project-tembea.firebaseapp.com',
    storageBucket: 'project-tembea.appspot.com',
    measurementId: 'G-9530RYLPQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaaE735sbbiNOzXn60XjNoviU_lrvf6dY',
    appId: '1:903105583227:android:d763d14c7ffb0d8912aade',
    messagingSenderId: '903105583227',
    projectId: 'project-tembea',
    storageBucket: 'project-tembea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfgAkkKsb3LgaIzEES8Vs0gm_ZJ3fSkTA',
    appId: '1:903105583227:ios:c546cc7c8799cf5712aade',
    messagingSenderId: '903105583227',
    projectId: 'project-tembea',
    storageBucket: 'project-tembea.appspot.com',
    iosBundleId: 'com.codeclimbers.tembeakenya',
  );
}
